apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uaoaij02d-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uaoaij02d-java-quarkus-gitops